export interface IProjectData {
  title: string;
  desc: string;
  stack: string[];
  github: string | null;
  preview: string | null;
  role: "author" | "contributor" | "maintainer" | "founder";
  status: "done" | "ongoing" | "closed";
  type?: "bounty" | "forked" | "featured" | "private";
}

export type TProjectData = Array<IProjectData>;

const projects: TProjectData = [
  {
    title: "Herald Protocol",
    desc: "I founded Herald Protocol and continue to lead it as CEO. It is a privacy-preserving notification infrastructure for Web3 that enables DeFi protocols to notify wallet addresses without ever learning the user's personal contact information. It combines on-chain encrypted identity registries with secure decryption inside AWS Nitro Enclaves and ZK-compressed delivery receipts via Light Protocol. The ecosystem spans nine repositories including Solana Anchor programs, NestJS gateways, Next.js dashboards, and published TypeScript SDKs.",
    stack: ["typescript", "rust", "nest.js", "solana", "anchor", "next.js", "aws"],
    github: "https://github.com/heraldhq-protocol",
    preview: null,
    role: "founder",
    status: "ongoing",
    type: "featured",
  },
  {
    title: "Solguard",
    desc: "[BOUNTY] Solguard is an autonomous bundle intelligence stack for Solana that monitors the network in real time, submits Jito bundles into valid leader windows, and prices tips dynamically. It uses AI-driven retry logic to track transactions across commitment levels and classify failures, reducing the complexity of profitable bundle submission.",
    stack: ["typescript", "solana", "node.js", "jito", "grpc"],
    github: "https://github.com/unnamed-lab/solguard",
    preview: null,
    role: "author",
    status: "ongoing",
    type: "bounty",
  },
  {
    title: "Solana Stablecoin Standard",
    desc: "[BOUNTY] An enterprise toolkit for deploying, managing, and governing stablecoins natively on Solana using the Token-2022 standard. It includes smart contracts, a CLI, a backend API, a frontend dashboard, a TypeScript SDK, and a terminal UI for comprehensive stablecoin operations.",
    stack: ["typescript", "rust", "anchor", "solana", "nest.js", "next.js"],
    github: "https://github.com/unnamed-lab/solana-stablecoin-standard",
    preview: null,
    role: "contributor",
    status: "ongoing",
    type: "bounty",
  },
  {
    title: "Trading Analytics Dashboard",
    desc: "[BOUNTY] A professional trading analytics dashboard for Solana that tracks profit and loss, generates equity curves, and provides AI-powered performance insights. Built for active traders who need clear visualisations of their trading activity and portfolio performance over time.",
    stack: ["typescript", "next.js", "solana", "prisma", "recharts", "tailwind css", "react"],
    github: "https://github.com/unnamed-lab/trading-analytics-dashboard",
    preview: null,
    role: "author",
    status: "ongoing",
    type: "bounty",
  },
  {
    title: "FutoNav",
    desc: "An offline-first campus navigation system built for the Federal University of Technology, Owerri. The Expo React Native app delivers turn-by-turn directions across campus buildings and landmarks with fuzzy search, delta sync, and full offline support via local SQLite caching.",
    stack: ["typescript", "expo", "react native", "supabase", "postgresql", "zustand", "fuse.js"],
    github: "https://github.com/unnamed-lab/futonav",
    preview: null,
    role: "author",
    status: "ongoing",
  },
  {
    title: "Agile PM",
    desc: "A modern agile project management platform for engineering teams that combines Kanban boards, sprint management, and deep analytics. It features burndown charts, Gantt visualisations, Pareto analysis, and PERT estimation to help teams plan, track, and deliver work more effectively.",
    stack: ["typescript", "next.js", "nest.js", "postgresql", "prisma", "tailwind css", "shadcn/ui"],
    github: "https://github.com/unnamed-lab/agile-pm",
    preview: null,
    role: "author",
    status: "ongoing",
  },
  {
    title: "Loan Eligibility System",
    desc: "A production-grade loan eligibility decision service that uses machine learning to assess applications with explainable results. Python trains an XGBoost model exported to ONNX, Rust serves the inference engine, and a NestJS API gateway orchestrates everything with SHAP explanations for regulatory compliance.",
    stack: ["python", "rust", "typescript", "nest.js", "postgresql", "docker", "onnx"],
    github: "https://github.com/unnamed-lab/loan-eligibilty-system",
    preview: null,
    role: "author",
    status: "done",
  },
  {
    title: "SentryShield",
    desc: "A Web3 security monitoring platform that integrates Solana wallet connectivity with Civic authentication for identity verification and threat detection. It gives users visibility into their wallet security posture and alerts them to potential risks.",
    stack: ["typescript", "next.js", "solana", "react", "tailwind css", "shadcn/ui"],
    github: "https://github.com/unnamed-lab/sentryshield",
    preview: null,
    role: "author",
    status: "ongoing",
  },
  {
    title: "E2E Chat",
    desc: "An end-to-end encrypted real-time chat backend built with NestJS and Socket.IO. It provides secure WebSocket communication with proper encryption protocols for private messaging applications.",
    stack: ["typescript", "nest.js", "socket.io", "node.js"],
    github: "https://github.com/unnamed-lab/e2e-chat",
    preview: null,
    role: "author",
    status: "done",
  },
  {
    title: "ASICT Election App",
    desc: "A secure student union election voting platform that handles voter authentication, ballot management, and real-time result tabulation. Built to ensure fair and transparent digital elections.",
    stack: ["typescript", "next.js", "postgresql", "prisma"],
    github: null,
    preview: null,
    role: "author",
    status: "done",
    type: "private",
  },
  {
    title: "Slipdeck",
    desc: "A comprehensive freelance contract and invoice management toolkit. It includes a NestJS backend API, a Next.js contract builder with rich text editing and PDF generation, client portal features, analytics dashboards, and AI-powered recommendations for freelancers managing their business.",
    stack: ["typescript", "next.js", "nest.js", "postgresql", "prisma", "stripe", "openai", "tailwind css"],
    github: null,
    preview: null,
    role: "author",
    status: "ongoing",
    type: "private",
  },
  {
    title: "Harbor",
    desc: "A Web3 marketplace platform frontend with Privy-based authentication, Wagmi Ethereum integration, and Reown AppKit for seamless wallet connectivity. Built as part of a broader decentralised marketplace ecosystem.",
    stack: ["typescript", "next.js", "react", "wagmi", "privy", "tailwind css", "shadcn/ui"],
    github: "https://github.com/Harbor2025/Harbor_FE",
    preview: null,
    role: "contributor",
    status: "ongoing",
  },
  {
    title: "ARK Platform",
    desc: "A multi-chain stablecoin platform supporting both Solana and Ethereum, built with Dynamic Labs Web3 authentication and TanStack Query for data management. I worked on the frontend to give users a single interface for interacting with stablecoins across different blockchain networks.",
    stack: ["typescript", "next.js", "react", "solana", "ethereum", "wagmi", "tailwind css"],
    github: "https://github.com/ARK-Labzz/ark-frontend",
    preview: null,
    role: "contributor",
    status: "ongoing",
  },
  {
    title: "Paragon",
    desc: "An admin platform with interactive analytics, role-based authentication, and data visualisations. I contributed to the backend, building API endpoints and database schemas that power the dashboard's metrics and user activity insights.",
    stack: ["typescript", "next.js", "react", "recharts", "nextauth.js", "framer motion", "tailwind css"],
    github: "https://github.com/paragondevorg/paragon-admin",
    preview: null,
    role: "contributor",
    status: "done",
  },
  {
    title: "Chatter",
    desc: "Marketing landing page for a business communication solution that I built with GSAP-powered animations and Chakra UI for a polished, responsive design. The site communicates Chatter's value proposition to potential users and drives sign-ups.",
    stack: ["typescript", "next.js", "react", "gsap", "framer motion", "chakra ui", "tailwind css"],
    github: "https://github.com/ChatterWalletHQ/chatter-landing",
    preview: null,
    role: "contributor",
    status: "done",
  },
  {
    title: "Music Minds",
    desc: "A backend API for a music platform built with NestJS, Prisma, and PostgreSQL. Handles content management, user data, and automated content processing using Puppeteer.",
    stack: ["typescript", "nest.js", "prisma", "postgresql", "puppeteer"],
    github: "https://github.com/musicmindsdev/music-minds-backend",
    preview: null,
    role: "contributor",
    status: "done",
  },
  {
    title: "The Beast Within",
    desc: "A digital comic reader website that delivers comic chapters through Cloudinary-optimised images, with user authentication and a custom reading experience. Readers can browse, purchase, and read comics in their browser.",
    stack: ["typescript", "next.js", "prisma", "postgresql", "nextauth.js", "cloudinary", "tailwind css"],
    github: "https://github.com/creatordrakon/the-beast-within-website",
    preview: null,
    role: "contributor",
    status: "done",
  },
];

export default projects;
