name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_plugins: "prettier-plugin-tailwindcss"
          prettier_options: --write **/*.{js,ts,jsx,tsx,md,mdx}
